- name: yum clean
  shell: yum clean all
- name: install pip
  yum:
    name:
      - python-pip
- name: Install openstacksdk library
  pip:
    name: openstacksdk
    state: latest
    extra_args: -U
- name: Create clouds.yaml file
  blockinfile:
    create: yes
    path: /etc/openstack/clouds.yaml
    block: |2
      clouds:
        ospcloud:
          auth:
            auth_url: http://192.168.0.20:5000/
            password: r3dh4t1!
            project_name: admin
            username: admin
          identity_api_version: '3.0'
          region_name: RegionOne
- name: Generate openstack.pub from openstack.pem
  hosts: localhost
  command: "ssh-keygen -y -f ~/.ssh/openstack.pem"
  register: openstack-pub
- name: Write the openstack public key
  hosts: localhost
  copy:
    content: "{{ openstack-pub.stdout }}"
    dest: "~/.ssh/openstack.pub"
- name: Set openstack.pub authorized key from file
  authorized_key:
    user: cloud-user
    state: present
    key: "{{ lookup('file', '~/.ssh/openstack.pub') }}"
